# Generated by Django 5.0.6 on 2024-05-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_tag_userquerylog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
    ]
